# Generated by Django 5.0 on 2024-01-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0002_remove_taskaddmodel_id_alter_taskaddmodel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteModel',
            fields=[
                ('title', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('status', models.CharField(default='Complete', max_length=10)),
            ],
        ),
    ]
