# Generated by Django 5.0 on 2024-01-19 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0003_completemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCompleteModel',
            fields=[
                ('taskaddmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='papp.taskaddmodel')),
                ('id', models.IntegerField()),
            ],
            bases=('papp.taskaddmodel',),
        ),
        migrations.DeleteModel(
            name='CompleteModel',
        ),
    ]
